apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
  namespace: vijay-gratitude
spec:
  replicas: 1
  selector:
    matchLabels:
      component: web
  template:
    metadata:
      labels:
        component: web
    spec:
      containers:
        - name: client
          image: prashantdey/merndemoapp:clientv1.5
          ports:
            - containerPort: 3000
