apiVersion: apps/v1
kind: Deployment
metadata:
  name: moods-api-deployment
  namespace: vijay-gratitude
spec:
  replicas: 1
  selector:
    matchLabels:
      component: moods-api
  template:
    metadata:
      labels:
        component: moods-api
    spec:
      containers:
        - name: moods-api
          image: 975050024946.dkr.ecr.eu-central-1.amazonaws.com/capstone-g3-gratitude/moods-api:v1.0.0-vijay
          ports:
            - containerPort: 5002
          env:
            - name: MOODS_SERVICE_ADDR
              value: moods-service-cluster-ip-service:50052
