apiVersion: apps/v1
kind: Deployment
metadata:
  name: stats-api-deployment
  namespace: vijay-gratitude
spec:
  replicas: 1
  selector:
    matchLabels:
      component: stats-api
  template:
    metadata:
      labels:
        component: stats-api
    spec:
      containers:
        - name: stats-api
          image: 975050024946.dkr.ecr.eu-central-1.amazonaws.com/capstone-g3-gratitude/stats-api:v1.0.0-vijay
          ports:
            - containerPort: 5003
          env:
            - name: STATS_SERVICE_ADDR
              value: stats-service-cluster-ip-service:50053
